# This file is released into the public domain. See COPYING.

name = "Vanguard Radio"
author = "SkinChangerDev"
prefix = "VGR"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0

[files]
include = [
    "COPYING",
    "VanguardRadio.so", # Linux binary
    "VanguardRadio.dll", # Windows 32-bit binary
    "VanguardRadio_x64.dll" # Windows 64-bit binary
]
