# This file is released into the public domain. See COPYING.

name = "Vanguard Radio"
author = "SkinChangerDev"
prefix = "VGR"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0

[files]
include = [
    "COPYING",
    "VanguardRadioIPC.so", # Linux binary
    "VanguardRadioIPC_x64.dll" # Windows binary
]
